language: python
python: '3.7'

cache:
  - pip

env:
  global:
    - APP_SETTINGS=DevConfig
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv check
  - make docker

after_success:
  - pipenv run codecov

branches:
  only:
    - master
